"""Adicionando coluna pepitas

Revision ID: f9501ff2c627
Revises: 79277d1e95d9
Create Date: 2026-09-30 02:45:27.648729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9501ff2c627'
down_revision: Union[str, Sequence[str], None] = '79277d1e95d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('pepitas', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'pepitas')
    # ### end Alembic commands ###
